// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9FjHL6IRkhOFMFq1HIEacIqEy7g4AJqk',
    appId: '1:1087273878944:web:08163d2456c384ee0990c5',
    messagingSenderId: '1087273878944',
    projectId: 'vvsamajapp',
    authDomain: 'vvsamajapp.firebaseapp.com',
    storageBucket: 'vvsamajapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiMZ7pEL5l4JYN2eEzC8GRx7pCeRKFD-o',
    appId: '1:1087273878944:android:1245068b6f2591ac0990c5',
    messagingSenderId: '1087273878944',
    projectId: 'vvsamajapp',
    storageBucket: 'vvsamajapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLpV5iHAw1pDqEc5jlhe1dmFH-JC_oxF0',
    appId: '1:1087273878944:ios:bc2a4c8a7408a5b80990c5',
    messagingSenderId: '1087273878944',
    projectId: 'vvsamajapp',
    storageBucket: 'vvsamajapp.firebasestorage.app',
    iosBundleId: 'com.example.vvsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLpV5iHAw1pDqEc5jlhe1dmFH-JC_oxF0',
    appId: '1:1087273878944:ios:bc2a4c8a7408a5b80990c5',
    messagingSenderId: '1087273878944',
    projectId: 'vvsamajapp',
    storageBucket: 'vvsamajapp.firebasestorage.app',
    iosBundleId: 'com.example.vvsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9FjHL6IRkhOFMFq1HIEacIqEy7g4AJqk',
    appId: '1:1087273878944:web:495269803876fc3f0990c5',
    messagingSenderId: '1087273878944',
    projectId: 'vvsamajapp',
    authDomain: 'vvsamajapp.firebaseapp.com',
    storageBucket: 'vvsamajapp.firebasestorage.app',
  );
}
